version: 1.0
provider:
  name: openfaas
  gateway: https://openfaas.lc.lcmvp.dockerps.io
functions:
  lc-get-orgs:
    lang: golang-middleware
    handler: ./lc-get-orgs
    image: dockerps/lc-get-orgs:latest
    environment:
      mysql_db: lc_orgs
      mysql_port: 3306
      allow_cors: "*"
      write_debug: true
    secrets:
      - mysql-host
      - mysql-username
      - mysql-password
